# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57b13fb371a09142fed6de96ade847b30d1b806f49e2ff88adb429c0843162d6665b303cc4001089d27872844487036770e9f41401a5d1cb06afd515c1e1ed17

test:
  secret_key_base: e9304600a82fadb5173326a621483db093460ed19df7828c17916da6b05bd0f17b74eaa1e76ac4aa39de6f68e690fd93c2638cfebc0508bae1d7075fbf441e9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
